---
on:
  push: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: make setup
      - name: Set skips on ci run
        run: |
          if [[ $GITHUB_REF_PROTECTED =~ "true" ]]; then
            echo "SKIP=no-commit-to-branch" >> $GITHUB_ENV
          fi
      - name: setup
        run: make setup
      - name: run pre-commit
        run: pre-commit run --show-diff-on-failure --all-files
        env:
          SKIP: "no-commit-to-branch,hadolint-docker"
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
